export const columns = [
  {
    id: "Company Name",
    label: "Company Name",
    // minWidth: 170,
    align: "right",
    format: (value) => value.toLocaleString("en-US"),
  },
  {
    id: "Email Address",
    label: "Email Address",
    // minWidth: 170,
    align: "right",
    format: (value) => value.toLocaleString("en-US"),
  },
  {
    id: "Phone no",
    label: "Phone no",
    // minWidth: 170,
    align: "right",
    format: (value) => value.toFixed(2),
  },
  {
    id: "Contact Person",
    label: "Contact Person",
    // minWidth: 170,
    align: "right",
    format: (value) => value.toFixed(2),
  },
  {
    id: "Facilitator",
    label: "Facilitator",
    // minWidth: 170,
    align: "right",
    format: (value) => value.toFixed(2),
  },
  {
    id: "Sites",
    label: "Sites",
    // minWidth: 170,
    align: "right",
    format: (value) => value.toFixed(2),
  },
  {
    id: "Tenants",
    label: "Tenants",
    // minWidth: 170,
    align: "right",
    format: (value) => value.toFixed(2),
  },
  {
    id: "Tenant Groups",
    label: "Tenant Groups",
    // minWidth: 170,
    align: "right",
    format: (value) => value.toFixed(2),
  },
  {
    id: "Actions",
    label: "Actions",
    // minWidth: 170,
    align: "right",
    format: (value) => value.toFixed(2),
  },
];

export const rows = [
  {
    "Company Name": "Infosys",
    "Email Address": "management@infosys.com",
    "Phone no": +919563214587,

    "Contact Person": "Vijayent Roy",
    Facilitator: "--",
    Sites: 12,
    Tenants: "--",
    "Tenant Groups": "Tenant Groups",
    Actions: "",
  },
  {
    "Company Name": "Wipro",
    "Email Address": "management@wipro.com",
    "Phone no": 9834687423,
    ext: +91,
    "Contact Person": "Kalpit Soni ",
    Facilitator: "--",
    Sites: 8,
    Tenants: "--",
    "Tenant Groups": "--",
    Actions: "",
  },
  {
    "Company Name": "Capgemini",
    "Email Address": "management@capgemini.com",
    "Phone no": 8432657995,
    ext: +91,
    "Contact Person": "Aisha Keer",
    Facilitator: "--",
    Sites: 6,
    Tenants: "--",
    "Tenant Groups": "--",
    Actions: "",
  },
  {
    "Company Name": "Lodha",
    "Email Address": "management@lodha.com",
    "Phone no": 9642357894,
    ext: +91,
    "Contact Person": "Kanika Khare",
    Facilitator: "--",
    Sites: 24,
    Tenants: 16,
    "Tenant Groups": "--",
    Actions: "",
  },
  {
    "Company Name": "Tata Consultancy Services",
    "Email Address": "management@tcs.com",
    "Phone no": 9632457468,
    ext: +91,
    "Contact Person": "Prabhat Rao ",
    Facilitator: "--",
    Sites: 10,
    Tenants: "--",
    "Tenant Groups": "--",
    Actions: "",
  },
  {
    "Company Name": "HCL",
    "Email Address": "management@hcl.com",
    "Phone no": 9452136487,
    ext: +91,
    "Contact Person": "Venkat Pant",
    Facilitator: "--",
    Sites: 5,
    Tenants: 2,
    "Tenant Groups": 1,
    Actions: "",
  },
  {
    "Company Name": "Redington ",
    "Email Address": "management@redington.com",
    "Phone no": 9326571865,
    ext: +91,
    "Contact Person": "Samir Yadav",
    Facilitator: "--",
    Sites: 1,
    Tenants: 1,
    "Tenant Groups": "--",
    Actions: "",
  },
];
